<?php

namespace Gumroad\DTOs;

class SaleDTO extends BaseDTO
{
    public function __construct(
        public string $id,
        public string $email,
        public string $seller_id,
        public string $timestamp,
        public string $daystamp,
        public string $created_at,
        public string $product_name,
        public bool $product_has_variants,
        public int $price,
        public int $gumroad_fee,
        public ?string $subscription_duration,
        public string $formatted_display_price,
        public string $formatted_total_price,
        public string $currency_symbol,
        public string $amount_refundable_in_currency,
        public string $product_id,
        public string $product_permalink,
        public bool $partially_refunded,
        public bool $chargedback,
        public string $purchase_email,
        public ?string $zip_code,
        public bool $paid,
        public bool $has_variants,
        public array $variants,
        public string $variants_and_quantity,
        public bool $has_custom_fields,
        public array $custom_fields,
        public int $order_id,
        public bool $is_product_physical,
        public string $purchaser_id,
        public bool $is_recurring_billing,
        public bool $can_contact,
        public bool $is_following,
        public bool $disputed,
        public bool $dispute_won,
        public bool $is_additional_contribution,
        public bool $discover_fee_charged,
        public bool $is_gift_sender_purchase,
        public bool $is_gift_receiver_purchase,
        public string $referrer,
        public array $card,
        public int $reviews_count,
        public int $average_rating,
        public ?string $subscription_id,
        public bool $cancelled,
        public bool $ended,
        public bool $recurring_charge,
        public ?string $license_key,
        public ?string $license_id,
        public bool $license_disabled,
        public ?string $affiliate,
        public ?string $offer_code,
        public int $quantity,
        public ?string $full_name,
        public ?string $street_address,
        public ?string $city,
        public ?string $state,
        public ?string $country,
        public ?string $country_iso2,
        public ?bool $shipped,
        public ?string $tracking_url,
        public ?string $sku_id,
        public ?string $sku_external_id,
        public $product_rating,
    ) {}


}
